@startuml casos-usos

left to right direction
skinparam packageStyle rectangle

' ====== ACTORES ======

actor Empleado 
actor Cajero 
actor "Asesor Financiero" as Asesor
actor "Gerente de Sucursal" as Gerente
actor Cliente 
actor "Sistema auditor" as Auditor

Empleado <|-- Cajero
Empleado <|-- Asesor
Empleado <|-- Gerente

' ====== SISTEMA ====== 
rectangle "Sistema de Gestión Bancaria (SGB)" {

    ' ====== GESTIÓN DE CLIENTES ======
    (Registrar Cliente Natural)
    (Registrar Cliente Empresarial)
    (Validar Datos Cliente)
    (Validar Cliente Existente)

    ' ====== GESTIÓN DE CUENTAS ======
    (Abrir Cuenta)
    (Validar Tipo de Cuenta)
    (Validar Cuenta Actia)
    (Bloquear Cuenta)
    (Desbloquear Cuenta)

    ' ====== TRANSACCIONES ======
    (Realizar Depósito)
    (Realizar Retiro)
    (Realizar Transferencia)
    (Validar Saldo Disponible)
    (Validar Cuentas)

    ' ====== GESTIÓN DE PERSONAL ======
    (Registrar Empleado)
    (Calcular Nómina)
    (Validar Datos Empleado)

    ' ====== CRÉDITOS ======
    (Aprobar Créditos)
    (Validar Permisos)

    ' ====== CONSULTAS ======
    (Consultar Cliente)
    (Registrar Auditoría)

    ' ====== RELACIONES ACTORES ======

    ' Cajero
     Cajero --> (Registrar Cliente Natural)
     cajero --> (Registrar Cliente Empresarial)
     cajero --> (Abrir Cuenta)
     Cajero --> (Realizar Depósito)
     Cajero --> (Realizar Retiro)

    ' Asesor 
      Asesor --> (Realizar Transferencia)
      Asesor --> (Consultar Cliente)
      Asesor --> (Bloquear Cuenta)
      Asesor --> (Desbloquear Cuenta)

    ' Gerente
    Gerente --> (Aprobar Créditos)
    Gerente --> (Registrar Empleado)
    Gerente --> (Calcular Nómina)

    ' Cliente
     Cliente --> (Notificar Cliente)

    ' Auditor
    Auditor --> (Consultar Historial de Transacciones)

    ' ====== INCLUDES (VALIDACIONES) ======

    (Registrar Cliente Natural) .> (Validar Datos Cliente) : <<include>>
    (Registrar Cliente Empresarial) .> (Validar Datos Cliente) : <<include>>

    (Abrir Cuenta) .> (Validar Cliente Existente) : <<include>>
    (Abrir Cuenta) .> (Validar Tipo de Cuenta) : <<include>>

    (Realizar Depósito) .> (Validar Cliente Existente) : <<include>>
    (Realizar Retiro) .> (Validar Cuenta Activa) : <<include>>
    (Realizar Retiro) .> (Validar Saldo Disponible) : <<include>>

    (Realizar Transferencia) .> (Validar Cuentas) : <<include>>

    (Registrar Empleado) .> (Validar Datos Empleado) : <<include>>

    (Aprobar Crdito) .> (Validar Permisos) : <<include>>

     ' ====== NOTIFICACIONES ======
     (Realizar Deposito) .> (Notificar Cliente) : <<include>>
     (Realizar Retiro) .> (Notificar Cliente) : <<include>>
     (Realizar Transferencia) .> (Notificar Cliente) : <<include>>

     ' ====== AUDITORÍA ======
     (Realizar Deposito) .> (Registrar Auditoria) : <<include>>
     (Realizar Retiro) .> (Registrar auditoria) : <<include>>
     (Realizar Transferencia) .> (Registrar Auditoria) : <<include>>
     (Abrir Cuenta) .> (Registrar Auditoria) : <<include>>
     (Registrar Cliente Natural) .> (Registrar Auditoria) : <<include>>
     (Registrar Cliente Empresarial) .> (Registrar Auditoria) : <<<include>>

     (Consultar Historial de Transacciones) .> (Registrar Auditoria) : <<include>>
}

@enduml