@startuml
left to right direction
skinparam packageStyle rectangle

actor "Cajero" as cajero
actor "Asesor Financiero" as asesor
actor "Gerente de Sucursal" as gerente
actor "Cliente" as cliente
actor "Sistema Auditor" as auditor

rectangle "Sistema de Gestión Bancaria Digital" {

    package "Gestión de Clientes y Cuentas" {
        (Registrar Cliente) as UC1
        (Registrar Cliente Natural) as UC1a
        (Registrar Cliente Empresarial) as UC1b
        (Abrir Cuenta) as UC2
        (Consultar Cliente) as UC6
        (Consultar Historial de Transacciones) as UC6b
        (Bloquear Cuenta) as UC7a
        (Desbloquear Cuenta) as UC7b

        (Validar Cliente Existente) as UC_VC
        (Validar Máximo 5 Cuentas) as UC_V5

        UC1a --|> UC1
        UC1b --|> UC1

        UC2 ..> UC_VC : <<include>>
        UC2 ..> UC_V5 : <<include>>
    }

    package "Gestión de Transacciones" {
        (Realizar Depósito) as UC3
        (Realizar Retiro) as UC4
        (Realizar Transferencia) as UC5

        (Validar Cuenta Activa) as UC_VA
        (Validar Saldo Suficiente) as UC_VS
        (Aplicar Comisión) as UC_Comision
        (Notificar Cliente) as UC11

        UC3 ..> UC_VA : <<include>>
        UC4 ..> UC_VA : <<include>>
        UC4 ..> UC_VS : <<include>>
        UC5 ..> UC_VS : <<include__

        UC4 ..> UC_Comision : <<include>>
        UC5 ..> UC_Comision : <<include>>

        UC3 ..> UC11 : <<extend>>
        UC4 ..> UC11 : <<extend>>
        UC5 ..> UC11 : <<extend>>
    }

    package "Gestión de Personal y Sucursal" {
        (Registrar Empleado) as UC9
        (Calcular Nómina) as UC10
        (Aprobar Crédito) as UC8

        (Calcular Bonificaciones y Antigüedad) as UC_Bonos
        (Verificar Permiso de Gerente) as UC_Permiso

        UC10 ..> UC_Bonos : <<include>>
        UC8  ..> UC_Permiso : <<include>>
    }

    package "Auditoría del Sistema" {
        (Consultar Historial de Modificaciones) as UC12
    }
}

cajero --> UC1
cajero --> UC2
cajero --> UC3
cajero --> UC4

asesor --> UC5
asesor --> UC6
asesor --> UC6b
asesor --> UC7a
asesor --> UC7b

gerente --> UC8
gerente --> UC9
gerente --> UC10

cliente --> UC11
auditor --> UC12

@enduml